api:
  build: api/.
  volumes:
    - "./app:/api/src/app"
  ports:
    - "8888:8080"
  links:
    - elasticsearch
web:
  build: web/.
  volumes:
    - "./web:/web"
  ports:
    - "3000:3000"
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
